Gambl/Controllers/CreateCourseController.cs
using Gambl.Data;
using Gambl.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gambl.Controllers
{
    public class CreateCourseController:Controller{
        private readonly DataContext _context;
        public CreateCourseController(DataContext context)
        {
            _context=context;
        }
        public async Task<IActionResult> Index(){
            
            return View(await _context.CourseInfos.ToListAsync());
        }
        public IActionResult CreateCourse(){
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCourse(CourseInfo model){
            _context.CourseInfos.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id){
            if(id==null){
                return NotFound();
            }
            var course=await _context.CourseInfos.FindAsync(id);
            if(course==null){
                return NotFound();
            }
            return View(course);
        }
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,CourseInfo model){
            if(id!=model.CourseId){
                return NotFound();
            }
            if(ModelState.IsValid){
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.CourseInfos.Any(o=>o.CourseId==model.CourseId)){
                        return NotFound();
                    }
                    else{
                        throw;

                    }
                
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
   
        [HttpGet]
        public async Task<IActionResult> Delete(int? id){
            if(id==null){
                return NotFound();
            }
            var course=await _context.CourseInfos.FindAsync(id);
            if(course==null){
                return NotFound();
            }
            return View(course);
        }
        [HttpPost]
        public async Task<IActionResult> Delete ([FromForm] int id){
            var course=await _context.CourseInfos.FindAsync(id);
            if(course==null){
                return NotFound();
            }
            _context.CourseInfos.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

Gambl/Views/CreateCourse/CreateCourse.cshtml
@model CourseInfo
<h2>Course Create</h2>
<hr>
<form asp-controller="CreateCourse" asp-action="CreateCourse">
    <div>
    <label asp-for="CourseName" class="form-label">CourseName</label>
    <input asp-for="CourseName" class="form-label">
    </div>
    <div>
    <label asp-for="CourseCategory" class="form-label">CourseCategory</label>
    <input asp-for="CourseCategory" class="form-label">
    </div>
    <div>
    <label asp-for="CourseExplain" class="form-label">CourseExplain</label>
    <input asp-for="CourseExplain" class="form-label">
    </div>
    <div>
    <label asp-for="CourseInstructor" class="form-label">CourseInstructor</label>
    <input asp-for="CourseInstructor" class="form-label">
    </div>
    <button type="submit">Kaydet</button>
    
</form>
<a href="/CreateCourse/Index">Listele</a>

Gambl/Views/CreateCourse/Delete.cshtml
<div>Silme</div>
@model CourseInfo
<p>
    <b>@Model.CourseName  </b> adlı kursu silmek ister msiiniz?
<form asp-action="Delete" method="post">
    <input type="hidden" name="id" value="@Model.CourseId">
    <button type="submit"> Evet</button>
    <a asp-action="Index">Hayır</a>
</form>
</p> 

Gambl/Views/CreateCourse/Edit.cshtml
<div>Güncelleme</div>
@model CourseInfo
<form asp-controller="CreateCourse" asp-action="Edit" class="form-label">
    <input type="hidden" asp-for="CourseId">
    <div>
        <label asp-for="CourseName" class="form-label">CourseName</label>
        <input asp-for="CourseName" class="form-label">
    </div>
    <div>
        <label asp-for="CourseCategory" class="form-label">CourseCategory</label>
        <input asp-for="CourseCategory" class="form-label">
    </div>
    <div>
        <label asp-for="CourseExplain" class="form-label">CourseExplain</label>
        <input asp-for="CourseExplain" class="form-label">
    </div>
    <div>
        <label asp-for="CourseInstructor" class="form-label">CourseInstructor</label>
        <input asp-for="CourseInstructor" class="form-label">
    </div>
    <button type="submit">Save</button>
</form>
<a href="/CreateCourse/Index">Course List</a>

Gambl/Views/CreateCourse/Index.cshtml
@model IEnumerable<CourseInfo>
    <h2>Course List</h2>
    <hr>
    <table>
        <thead>
        <tr>
            <th>@Html.DisplayNameFor(m =>m.CourseName) </th>
            <th>@Html.DisplayNameFor(m =>m.CourseCategory)</th>
            <th>@Html.DisplayNameFor(m =>m.CourseExplain)</th>
            <th>@Html.DisplayNameFor(m =>m.CourseInstructor)</th>

        </tr>

           
        </thead>
        <tbody>
            @foreach(var a in Model)
            {
            <tr>
                
                <td>@Html.DisplayFor(modelItem=>a.CourseName)</td>
                <td>@Html.DisplayFor(modelItem=>a.CourseCategory)</td>
                <td>@Html.DisplayFor(modelItem=>a.CourseExplain)</td>
                <td>@Html.DisplayFor(modelItem=>a.CourseInstructor)</td>
                <td>
                    <a asp-controller="CreateCourse" asp-action="Edit" asp-route-id="@a.CourseId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-controller="CreateCourse" asp-action="Delete" asp-route-id="@a.CourseId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>

            }
            
        </tbody>
    </table>